version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - 8888:80
    restart: "no"
    env_file:
      - .env
    volumes:
      - .:/myportfolio
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data

volumes:
  mydatabase:
